# Generated by Django 5.0.2 on 2024-02-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorits',
        ),
    ]
